name: client
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  smooth_page_indicator: ^1.2.1
  get: ^4.7.2
  device_preview: ^1.2.0
  flutter_svg: ^2.2.1
  get_storage: ^2.1.1
  showcaseview: ^4.0.1
  animations: ^2.0.11
  carousel_slider: ^5.1.1
  table_calendar: ^3.1.3
  intl: ^0.19.0
  credit_card_scanner: ^1.0.5

  # Local storage & encryption
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/countrycode.json
    - assets/images/
    - assets/icons/
